# https://yunohost.org/en/packaging_manifest
packaging_format = 2

id = "zigbee2mqtt"
name = "Zigbee2MQTT"
description.en = "Zigbee2MQTT as YunoHost package"

version = "1.35.1~ynh1"

maintainers = ["Jens Diemer"]


[upstream]
# https://yunohost.org/en/packaging_manifest#upstream-section
license = "GPL-3.0-or-later"
# website = "https://github.com/YunoHost-Apps/zigbee2mqtt_ynh" # If the app has no proper website, just remove the 'website' key entirely
admindoc = "https://github.com/YunoHost-Apps/zigbee2mqtt_ynh"
userdoc = "https://github.com/Koenkk/zigbee2mqtt"
code = "https://github.com/YunoHost-Apps/zigbee2mqtt_ynh"



[integration]
# https://yunohost.org/en/packaging_manifest#integration-section
yunohost = ">=11"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M" # **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...



[install]
# https://yunohost.org/en/packaging_manifest#install-questions

    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"
    default = "admin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.serial_port] # __SERIAL_PORT__
    ask.en = "Serial port of our Zigbee adapter"
    type = "string"
    example = "/dev/serial/by-id/your-CC2652RB_usb_stick_id"
    default = "/dev/ttyUSB0"
    help.en = "See also: https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html - Use 'ls /dev/serial/by-id/*' to find the correct serial port."


[resources]
    [resources.sources.main]
    url = "https://github.com/Koenkk/zigbee2mqtt/archive/refs/tags/1.35.1.tar.gz"
    sha256 = "d60ca815eef0f53cad4f1a3adb642257e2aa86bb7b225f7992e080b8c92492e2"
    autoupdate.strategy = "latest_github_tag"
    prefetch = true # Store in "/var/cache/yunohost/download/$app/$source_id" for "ynh_setup_source"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # https://yunohost.org/en/packaging_apps_resources#install-dir
    # This will create/remove the install dir as /var/www/$app/
    # and store the corresponding setting $install_dir and template variable __INSTALL_DIR__

    [resources.permissions]
    # https://yunohost.org/en/packaging_apps_resources#permissions
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # https://yunohost.org/en/packaging_apps_resources#ports
    # This will pick a random port for reverse-proxying and store it as the $port setting
